apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-postgres-service-host
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-postgres-service-host
      type: secret
  output:
    secret:
      name: backstage-secret-postgres-service-host
      dataKey: POSTGRES_SERVICE_HOST