apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-pt0-k8s-cluster-url
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-pt0-k8s-cluster-url
      type: secret
  output:
    secret:
      name: backstage-secret-pt0-k8s-cluster-url
      dataKey: PT0_K8S_CLUSTER_URL