apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-clustername-pd0
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-clustername-pd0
      type: secret
  output:
    secret:
      name: backstage-secret-clustername-pd0
      dataKey: K8S_CLUSTER_NAME_DEV