apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-jira-api-token
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-jira-api-token
      type: secret
  output:
    secret:
      name: backstage-secret-jira-api-token
      dataKey: JIRA_API_TOKEN