apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-snyk-token
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-snyk-token
      type: secret
  output:
    secret:
      name: backstage-secret-snyk-token
      dataKey: SNYK_TOKEN