apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-postgres-user
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-postgres-user
      type: secret
  output:
    secret:
      name: backstage-secret-postgres-user
      dataKey: POSTGRES_USER