apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-github
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-github
      type: secret
  output:
    secret:
      name: backstage-secret-github
      dataKey: GITHUB_TOKEN