apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-postgres-service-port
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-postgres-service-port
      type: secret
  output:
    secret:
      name: backstage-secret-postgres-service-port
      dataKey: POSTGRES_SERVICE_PORT