apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-custom-domain-uri
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-custom-domain-uri
      type: secret
  output:
    secret:
      name: backstage-secret-custom-domain-uri
      dataKey: CUSTOM_DOMAIN_URI