apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-jfrog-host-url
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-jfrog-host-url
      type: secret
  output:
    secret:
      name: backstage-secret-jfrog-host-url
      dataKey: JFROG_HOST_URL