apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backstage-secret-azuredevops-orgname
  namespace: backstage-dev
spec:
  vault:
    name: kv-shared-services-gkh
    object:
      name: backstage-secret-azuredevops-orgname
      type: secret
  output:
    secret:
      name: backstage-secret-azuredevops-orgname
      dataKey: AZURE_DEVOPS_ORG_NAME