---

- hosts: all
  collections:
    - community.windows

- name: Install default apps
  hosts: all
  gather_facts: false
  tasks:
  - ansible.windows.win_file:
    path: C:\temp
    state: directory

